Numpy-unit-conversion
309thEDDGE/bip pull request #4
Opened 2024-07-30 18:57 UTC by gzusaf

Numpy 2.0.0 will no longer implicitly convert the datatypes of units during calculations.
This MR explicitly changes the datatypes of variables that will exceed the bounds of uint32.

2024-07-30 18:58 UTC, gzusaf commented on tests/juliet/test_data_context_packet.py
> +    assert packet.freq == 17592.186044415
This test change requires an explaination:
The equation for calculating frequency is: ((word1 << 32) | word2) * (10**-9) * (2**-20))
In the Mock data word1 = 0xFFFFFFFF (4294967295) and word2 = 0xFFF00000 (4293918720)
word1 << 32 = 0xFFFFFFFF00000000 (18446744069414584320)
word1 << 32 | word2 = 0xFFFFFFFFFFF00000 (18446744073708503040)
18446744073708503040* 10^-9 *2^-20 = 17592.186044415

I don't know how this ever equaled -.000000001

2024-07-30 18:58 UTC, gzusaf commented on tests/tango/test_signal_data_packet.py
> +    assert packet.time == 65535.000268435455
This test change requires an explaination:
In the Mock data TSI = 0x0000FFFF, TSF0 = 0x00000000, and TSF1=0x10000000.
The equation to determine time is TSI + ((TSF0 << 32) + TSF1) *1e-12. TSF0 and TSF1 are the fractional parts of time while TSI is the integer part.
65535.000268435455 is the correct answer for time given our mock data. The previous test was written incorrectly. 1218456.504606846976 would be the correct answer is TSF1 = 0x1000000000000000. This is where I believe the problem arose.
Numpy's implicit conversion from uint32 to int64 changed the data and produced an erroneous result.

2024-08-01 15:43 UTC, RR-USAF requested changes
From the Zen of Python
> Explicit is better than implicit

So I like the explicit conversion (even though it was forced on us by Pandas).

I'm not sure we need 4 lines for most of these functions.

2024-08-01 15:43 UTC, RR-USAF commented on setup.cfg
> -python_requires = >=3.9
why do we need 3.11?

2024-08-01 15:43 UTC, RR-USAF commented on src/bip/common/bit_manipulation.py
> +    raw_data = (word1 << 32) | word2
i dislike taking 3 lines and intermediate variables for something that's obvious.

```
raw_data = (np.uint64(word1) << 32) | np.uint64(word2)
```
or even roll this line and the next together.

2024-08-01 15:43 UTC, RR-USAF commented on src/bip/common/bit_manipulation.py
> +    return np.uint32(raw_data * (10**-6) * (2**-20))
why are we converting to a uint32?

2024-08-01 15:43 UTC, RR-USAF commented on src/bip/common/bit_manipulation.py
it's not clear to me that this file needs to exist.  all of these functions are 1 or two logic lines that *i think* would be clearer at the source.

2024-08-02 14:58 UTC, gzusaf commented on src/bip/common/bit_manipulation.py
The file's purpose was to extract a lot of these little logic pieces that are common to both Tango and Juliet. 
I don't have strong opinions on keeping it or not

2024-08-02 14:58 UTC, gzusaf commented on src/bip/common/bit_manipulation.py
> +    return np.uint32(raw_data * (10**-6) * (2**-20))
good catch, that was a mistake on my part

2024-08-02 14:58 UTC, gzusaf commented on src/bip/common/bit_manipulation.py
> +    raw_data = (word1 << 32) | word2
Agreed. Fixed

2024-08-02 15:03 UTC, gzusaf commented on setup.cfg
> -python_requires = >=3.9
I don't actually remember. numpy 2 and pyarrow 17 should only need 3.9.
I'll test this and comment again

2024-08-02 22:01 UTC, gzusaf commented on setup.cfg
> -python_requires = >=3.9
python 3.9 works just fine. I must've hallucinated an error.

2024-08-09 16:22 UTC, RR-USAF commented on src/bip/common/bit_manipulation.py
> +    return np.uint32(raw_data * (10**-6) * (2**-20))
still needs resolved.

2024-08-09 16:23 UTC, RR-USAF commented on src/bip/common/bit_manipulation.py
> +    return np.float64(raw_data * (10**-6) * (2**-20))
what is offset?

2024-08-09 16:24 UTC, RR-USAF commented on src/bip/common/bit_manipulation.py
> +    return np.float64(np.uint64(tsi) +\
gratuitous conversions

2024-08-09 16:24 UTC, RR-USAF requested changes
still a few open questions.

2024-08-12 23:34 UTC, gzusaf commented on src/bip/common/bit_manipulation.py
> +    return np.float64(np.uint64(tsi) +\
removed

2024-08-12 23:36 UTC, gzusaf commented on src/bip/common/bit_manipulation.py
> +    return np.float64(raw_data * (10**-6) * (2**-20))
I don't know. It's a part of Juliet's Extension Command packets and it's measured in GHz, that's what I can tell just from bip.
I'd check the Vita 49.2 spec, but the only way I know how to open that is through Remote Desktop which we've lost access to

2024-08-23 14:02 UTC, hh-usaf approved these changes

2024-09-25 14:55 UTC, RR-USAF approved these changes
seems good.

2024-09-25 16:19 UTC, JK-USAF reviewed
It looks pretty good.

2024-09-25 19:31 UTC, merged